name: Angular Project CI-CD-CD
on:
  push:
    branches:
      - 'release/**'
      - 'feature/**'
  workflow_dispatch:
  schedule:
    - cron: '45 19 * * 1'   
    - cron: '00 00 * * 1' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Test
        run: |
          npm run test:ci   
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist 
  build_docker_image_and_push_to_docker_hub:
    runs-on: ubuntu-latest 
    needs: test   
    steps: 
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Generar imagen docker y push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: marcosht4/angular-workflow-app:latest
  deploy_into_dev_server:
    runs-on: ubuntu-latest
    needs: [test, build, build_docker_image_and_push_to_docker_hub]
    steps:
      - name: Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker stop ANGULAR_SERVICE
            sudo docker rm ANGULAR_SERVICE
            sudo docker run -d -p 8080:80 --name ANGULAR_SERVICE marcosht4/angular-workflow-app:latest                    
              

